### ISSUE TITLE
Foto Berria en últimas noticias

### ISSUE THREAD

**Issue by LauraErrea** [LauraErrea/Berria#31]
En la página de últimas noticias, las firmas que son de Berria deben llevar la fotico del icono. 

![WhatsApp Image 2023-11-10 at 14 21 23 (4)](https://github.com/LauraErrea/Berria/assets/148250993/6d130323-b60f-4460-962b-d705856b0d42)

**Comment by spanisello24** [comment]
@pellour se debería asignar imagen al autor Berria.

**Comment by spanisello24** [comment]
Ya lo hemos corregido nosotros.
