### ISSUE TITLE
Texto aviso de añadir una tag

### ISSUE THREAD

**Issue by LauraErrea** [LauraErrea/Berria#34]
El aviso de login se corta por arriba. El texto tendría que estar por debajo del aspa de cerrar.

![WhatsApp Image 2023-11-10 at 14 47 23](https://github.com/LauraErrea/Berria/assets/148250993/f54d46d6-9c11-4514-8ca7-6cf259049efe)

**Comment by spanisello24** [comment]
@LauraErrea no conseguimos ver en qué pantalla se produce este error... ¿nos lo puedes indicar?
Gracias.

**Comment by LauraErrea** [comment]
Ya no puedo porque salía cuando dabas el botón de seguir un tag.
