### ISSUE TITLE
Firmas - categoría

### ISSUE THREAD

**Issue by LauraErrea** [LauraErrea/Berria#38]
En las firmas por debajo está cogiendo el lugar en vez de la categoría. 

![Captura de pantalla 2023-11-13 a las 16 54 48](https://github.com/LauraErrea/Berria/assets/148250993/649e10d9-10c4-4bbd-828c-ea7c0bc16ce6)

**Comment by spanisello24** [comment]
Es correcto, no? es lo que hay en el diseño... la categoría se muestra por encima del artículo.
Confirmas @pellour

**Comment by pellour** [comment]
Sí, es correcto. Queremos que muestre el lugar. 
En el diseño en la home y en las portadas de sección se pintó la categoría. Pero no lo vemos. Por tanto, no queremos pintar la categoría en la firma.
