### ISSUE TITLE
Apertura podcast

### ISSUE THREAD

**Issue by LauraErrea** [LauraErrea/Berria#41]
Los textos pequeños en Feature Flat, tienen que ser text, salen con la tipografía de titular. 
La columna del titular en la apertura quedaría mejor si esa columna fuera más estrecha. 
En el slide de podcast no sale el play de cada pieza. También sale mal la tipografía y es mejor que los textos fuesen más cortos (sobre todo para el móvil).

![Captura de pantalla 2023-11-17 a las 10 00 48](https://github.com/LauraErrea/Berria/assets/148250993/a906c864-d31b-4717-9a3f-c021951f6e35)
![Captura de pantalla 2023-11-17 a las 10 00 11](https://github.com/LauraErrea/Berria/assets/148250993/e9b94f94-182d-430a-8862-283bbebe9db1)

**Comment by spanisello24** [comment]
Cambios de tipografía aplicados. Sobre el play, se hizo un cambio de funcionamiento del slide para focalizar la interacción arriba.

**Comment by LauraErrea** [comment]
Los textos que habéis cambiado son con la Feature Flat Text, no con la Graphik.

**Comment by LauraErrea** [comment]
Quizá más adelante tengamos que revisar este slide porque creo que no se entiende muy bien la funcionalidad, quizá con las imágenes del slide más pequeñas... Pero lo dejamos para después de la salida.

**Comment by pellour** [comment]
Sí, yo también creo que hay que revisar, lo he comentado un día de estos con Gerad. Pero no podemos cambiar ahora.

**Comment by spanisello24** [comment]
Tipografía modificada. Sobre el funcionamiento del slide lo comentamos los próximos días con Pello.
