### ISSUE TITLE
Listado de tag

### ISSUE THREAD

**Issue by LauraErrea** [LauraErrea/Berria#44]
Los titulares de los listados salen todos en light.
En estos listados no debería aparecer opinión ya que hay una columna a la derecha para eso. 

![Captura de pantalla 2023-11-17 a las 10 18 23](https://github.com/LauraErrea/Berria/assets/148250993/faaee3d2-7c7b-4e68-9262-e4222ec22aea)

**Comment by spanisello24** [comment]
Los estilos de los titulares han quedado corregidos.
El tema de no mostrar opinión en la izquierda hay que mirarlo y nos lo ha reportado Pello también, ahora mismo no es viable.
