### ISSUE TITLE
Cabecera recetas

### ISSUE THREAD

**Issue by LauraErrea** [LauraErrea/Berria#51]
En las recetas sale la cabecera de Bizigiro

![Captura de pantalla 2023-11-17 a las 10 46 56](https://github.com/LauraErrea/Berria/assets/148250993/128a76f5-7bb9-45b1-be98-58cb48a4bb3d)

**Comment by spanisello24** [comment]
Lo que mostramos es la categoría padre del artículo, que en este caso es Bizigiro.
<img width="256" alt="image" src="https://github.com/LauraErrea/Berria/assets/148543925/f784e78a-f09c-4808-bd43-5f11dae803d8">

**Comment by pellour** [comment]
ESto lo comentaba en una de las revisiones:

De momento sólo publicamos recetas de un cocinero (Iker Markinez) y por tanto sólo
deberíamos tener una categoría de recetas: “Iker Markinezen errezetak”. (Si en futuro hay
más cocineros ya veremos cómo lo hacemos).
Pero la categoría “Iker Markinezen errezetak” la hemos colocado mal. La hemos puesto
dentro de la sección Bizigiro. Pero no es correcto. En el papel las recetas van dentro se esa
sección, pero en internet no tiene sentido.
Por tanto, debemos definir en ATALAK una categoría principal ERREZETAK y dentro de ella
una secundaria IKER MARKINEZEN ERREZETAK. Para tener identificadas las recetas de
Markinez, por si un día cambiamos de cocinero.
De momento, como sólo tenemos un cocinero, nos vale con la página https://
www.berria.eus/errezetak.html , pero deberíamos ajustar la URL de esta manera: berria.eus/
errezetak/iker-markinezen-errezetak.html.
En cambio, la página https://www.berria.eus/bizigiro/iker-markinezen-errezetak , estaría de
sobra.
