### ISSUE TITLE
Podcast Listado

### ISSUE THREAD

**Issue by LauraErrea** [LauraErrea/Berria#54]
En el listado de un podcast hay mucha distancia entre la imagen de apertura y donde empieza el listado. 

![Captura de pantalla 2023-11-17 a las 14 41 41](https://github.com/LauraErrea/Berria/assets/148250993/5107ba67-3522-4ea5-bac6-dae797f92ecc)

**Comment by pellour** [comment]
Eso es por las medidas de la foto.
Falta poner el nombre del autor del podcast.
