### ISSUE TITLE
Publicidad

### ISSUE THREAD

**Issue by LauraErrea** [LauraErrea/Berria#57]
Hay publicidad que no se carga, no sé si es que no se ha metido o es que hay algún problema...

![Captura de pantalla 2023-11-20 a las 8 34 34](https://github.com/LauraErrea/Berria/assets/148250993/535dfe29-637f-4ae0-93fd-78e532367341)

**Comment by pellour** [comment]
Falta código en tres posiciones. Se lo he pasado.

**Comment by spanisello24** [comment]
Resuelto.
