### ISSUE TITLE
Cabecera de tag

### ISSUE THREAD

**Issue by LauraErrea** [LauraErrea/Berria#64]
Hay algún tag que en la cabecera no sale bien

![Captura de pantalla 2023-11-20 a las 9 03 24](https://github.com/LauraErrea/Berria/assets/148250993/3e581e99-429e-4f7d-a20c-0bc6a8d434e5)

**Comment by spanisello24** [comment]
Hola @LauraErrea lo que nos mandas es un autor: https://www.berria.eus/atef-abu-saif_72894_115.html 
En este caso, la visualización es correcta aunque falta la imagen y la bio, que no deben estar rellenadas en el gestor.
